apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: p4vwn7r3y-java-quarkus
  janus-idp.io/tekton: p4vwn7r3y-java-quarkus
  backstage.io/kubernetes-id: p4vwn7r3y-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: p4vwn7r3y-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
